language: android
jdk:
  - oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - tools # TODO https://github.com/travis-ci/travis-ci/issues/6193
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-28
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
  - mkdir $ANDROID_HOME/licenses
  - cp -rf .travis_licenses/* $ANDROID_HOME/licenses
script: "./gradlew $TASK"
env:
    - TASK="lintDebug"
    - TASK="testDebug"
